name: Ubuntu compilation and tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --features async
      - name: Install tshark
        run: sudo apt-get install -y tshark
      - name: Run doc tests
        run: cargo test --doc --features async
      - name: Run unit tests
        run: cargo test --lib --features async -- --test-threads=1
