name: Windows compilation and tests 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-2019 

    steps:
    - name: Install Chocolatey and wireshark
      shell: powershell
      run: Install-Module -Name TShark -RequiredVersion 1.0.2
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
